version: 2.1

executors:
  gulp-executor:
    docker:
      - image: opennms/gulp:4.0.0-b1

  ghr-executor:
    docker:
      - image: opennms/ghr:0.12.0-b1

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy-github:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  build:
    executor: gulp-executor
    steps:
      - checkout

      - run: |
          yarn install

      - run: |
          gulp bundle
      
      - run: |
          gulp bundle:pack

      - store_artifacts:
          path: build/ui-bundle.zip
          destination: ui-bundle.zip

      - persist_to_workspace:
          root: ~/
          paths:
            - project

  deploy-github:
    executor: ghr-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Push UI bundle archive to GitHub
          command: |
            source release.version
            ghr -replace -u "${GITHUB_USER}" -r "${GITHUB_REPO}" -n "${codename}" "v${release}" build/ui-bundle.zip
